services:
  reactapp:
    build: ./client
    container_name: react_vite_app
    networks:
      - directus_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client1.rule=Host(`lv.hotanloc.xyz`)"
      - "traefik.http.routers.client1.entrypoints=websecure"
      - "traefik.http.routers.client1.tls.certresolver=letsencrypt"
      - "traefik.http.routers.client1.service=client1"
      - "traefik.http.services.client1.loadbalancer.server.port=8000"

  server:
    user: "node"
    container_name: server
    build:
      context: ./server
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - directus_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`lv-server.hotanloc.xyz`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"
      - "traefik.http.routers.client.service=client"
      - "traefik.http.services.client.loadbalancer.server.port=5000"
    depends_on:
      - postgres
      - reactapp

  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123123}
      POSTGRES_DB: ${POSTGRES_DB:-article}
      PGDATA: ./data/postgres
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - directus_traefik
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-holoc22102001@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - directus_traefik
    restart: unless-stopped

  directus:
    image: directus/directus
    volumes:
      - ./uploads:/directus/uploads

      - ./extensions:/directus/extensions
    depends_on:
      - postgres
    # env_file: .env
    environment:
      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "pg"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "article"
      DB_USER: "postgres"
      DB_PASSWORD: "123123"

      ADMIN_EMAIL: "holoc22102001@gmail.com"
      ADMIN_PASSWORD: "locvtc123"
      CORS_ENABLED: true
      CORS_ORIGIN: "*"
      CORS_METHODS: "GET,POST,PATCH,DELETE"
      WEBSOCKETS_ENABLED: true
      WEBSOCKETS_HEARTBEAT_ENABLED: false
    # ports:
    #   - 8057:8055
    networks:
      - directus_traefik

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lv-directus.rule=Host(`lv-directus.hotanloc.xyz`)"
      - "traefik.http.routers.lv-directus.entrypoints=websecure"
      - "traefik.http.routers.lv-directus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.lv-directus.service=lv-directus"
      - "traefik.http.services.lv-directus.loadbalancer.server.port=8055"

networks:
  directus_traefik:
    external: true

volumes:
  postgres:
  pgadmin:
